#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V
bspc monitor DisplayPort-0 -d VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config border_radius        20
# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule --add Megasync state= pseudo_tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule --add Alacritty state= pseudo_tiled

# feh --bg-scale ~/Pictures/wallpaper.jpg
python ~/.config/bspwm/background.py &
setxkbmap latam &
dunst &
picom &
#este es para polybar


mpd &
# mpc play &
# xterm &
konsole &
discord &
# brave &
firefox &
clickup &

# picom --experimental-backends
# glava --desktop --force-mod=graph
# megasync &


if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m sh ~/.config/polybar/launch.sh --forest &
    MONITOR=$m plank -n dock1 & plank -n dock2 &
  done
else sh ~/.config/polybar/launch.sh &
fi

#low battery notification
BATTINFO=`acpi -b`
if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
    DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO"
fi

[ ! -s ~/.config/mpd/pid ] && mpd
