#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0 -d VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config border_radius        20
# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule --add Megasync state= pseudo_tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule --add Alacritty state= pseudo_tiled

feh --bg-scale ~/Pictures/wallpaper.jpg
setxkbmap latam

picom &
#este es para polybar


# mpd &
# mpc play &
# xterm &
# discord &
brave &
# firefox &
# picom --experimental-backends
# glava --desktop --force-mod=graph
# megasync &
setxkbmap latam &
plank &

dual monitor setup
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m sh ~/.config/polybar/launch.sh --material &
    # MONITOR=$m plank -n dock1 & plank -n dock2 &
  done
else sh ~/.config/polybar/launch.sh --material &
fi

# sh ~/.config/polybar/launch.sh --material  &
sh ~/scripts/screen.sh --material  &
# //low battery notification
# BATTINFO=`acpi -b`
# if [[ `echo $BATTINFO | grep Discharging` && `echo $BATTINFO | cut -f 5 -d " "` < 00:15:00 ]] ; then
#     DISPLAY=:0.0 /usr/bin/notify-send "low battery" "$BATTINFO"
# fi

[ ! -s ~/.config/mpd/pid ] && mpd
